name: Deploy React App to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy-and-deploy:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build React App
        run: npm run build

      - name: Deploy to Firebase Hosting
        uses: w9jds/firebase-action@v12.9.0
        wtih:
          args: deploy --only hosting --project fir-47a53
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}



